---
- name: update apt
  apt: >
    update_cache=yes
    cache_valid_time=3600

- name: install deps
  apt: >
    pkg={{item}}
    state=installed
  with_items:
    - unzip

- name: create consul-template directory structure
  file: >
    state=directory
    path={{ item }}
  with_items:
    - "{{ consul_template_home }}"
    - "{{ consul_template_home }}/bin"
    - "{{ consul_template_home }}/config"
    - "{{ consul_template_home }}/templates"
    - "{{ consul_template_home }}/releases"

- name: download consul-template binary
  get_url:
    url: "{{ consul_template_download_url }}"
    dest: "/tmp"

- name: unzip the downloaded package
  unarchive:
    src: "/tmp/{{ consul_template_archive_file }}"
    dest: "{{ consul_template_home }}/releases/"
    copy: no
    owner: "root"
    group: "root"
    mode: "0755"
    creates: "{{ consul_template_home }}/releases/{{ consul_template_release }}/{{ consul_template_binary }}"

- name: link new release to bin directory
  file:
    src: "{{ consul_template_home }}/releases/{{ consul_template_release }}/{{ consul_template_binary }}"
    dest: "{{ consul_template_home }}/bin/{{ consul_template_binary }}"
    owner: root
    group: root
    mode: "0755"
    state: link

- name: copy consul-template systemd service configuration
  template: >
    src=consul-template.service.systemd.j2
    dest=/etc/systemd/system/consul-template.service
    mode=0755
  when: consul_template_use_systemd

- name: copy consul-template upstart service configuration
  template: >
    src=consul-template.service.upstart.j2
    dest=/etc/init/consul-template.conf
    mode=0755
  when: consul_template_use_upstart

- name: add consul-template to path through profile.d
  template: >
    src=consul-template.sh.j2
    dest=/etc/profile.d/consul-template.sh
    owner=root
    group=root
    mode=0755

- name: consul-template config file
  template: >
    src={{ consul_template_config_file_template }}
    dest={{ consul_template_home }}/config/{{ consul_template_config_file }}
    mode=0755

- name: install templates
  copy:
    src: "{{ item.source }}"
    dest: "{{ consul_template_home }}/templates/{{ item.source | basename }}"
    owner: "root"
    group: "root"
    mode: "0755"
  with_items:
    - "{{consul_template_templates}}"
